version: '3.4'

services:
  redis:
    image: redis:alpine
    command: ["redis-server", "--appendonly", "yes"]
    restart: always
    ports:
      - 6380:6379
    volumes:
      - /srv/data/docker/containers/redis-app/data:/data
    environment:
      TZ: Europe/Rome
